server:
  port: 3000
  servlet:
    context-path: /store

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: env.properties
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  cloudfront:
    name: dyg4oa4f8q8zk
  bucket:
    name: mysinglestore3

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds